steps:
# Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  id: 'install-dependencies'
  args: ['install']

# Unit test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:unit']

# Build the new docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/explore-muay:latest', '.']

# Run the app and dependencies in the background using docker-compose.
# Warning: this won't be cleaned up, which might be an issue if you run it
# with the local builder.
# - name: 'docker/compose:1.15.0'
#   args: ['up', '-d']
#   env:
#   - 'PROJECT_ID=$PROJECT_ID'

# Run the integration tests against the running docker-compose stack.
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'test:e2e']
#   env:
#   - 'HOST=counter' # running container, container_name defined in the docker-compose.yml
#   - 'PORT=50051'

# deploy to cloud run
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'muay-app', '--image', 'gcr.io/$PROJECT_ID/explore-muay:latest', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']

# Push the new image to the registry.
images: ['gcr.io/$PROJECT_ID/explore-muay:latest']
