version: '2'

services:
  app:
    image: gcr.io/$PROJECT_ID/explore-muay:latest
    container_name: muay-app
    depends_on:
      - redis
    ports:
      - "50051:50051"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
    default:
        external:
            name: cloudbuild
